from pathlib import Path
import json,hashlib,shutil,html
OUT=Path(__file__).resolve().parent;ROOT=OUT.parents[3];WORK=ROOT/'work/illustrated-damage';SOURCE=WORK/'native-final'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
validation=json.loads((SOURCE/'validation.json').read_text());assert validation['checks']==3832 and validation['failures']==0
assert len(validation['captures'])==39 and len(validation['bodies'])==23
(OUT/'native').mkdir(exist_ok=True);(OUT/'evidence/first-pass').mkdir(parents=True,exist_ok=True)
rows=[]
for entry in validation['captures']:
 source=Path(entry['path']);assert sha(source)==entry['sha256'];target=OUT/'native'/source.name;shutil.copyfile(source,target);assert sha(target)==entry['sha256']
 first=WORK/'native-first-pass'/source.name;assert sha(first)==entry['sha256']
 rows.append({'first_pass_byte_identical':True,'source':str(source),'path':str(target.relative_to(OUT)),'sha256':entry['sha256'],'size':entry['size']})
for source,target in [(WORK/'root-native-art-review.json',OUT/'evidence/root-native-art-review.json'),(WORK/'native-review-fighter-art/review.json',OUT/'evidence/fighter-art-native-review.json'),(SOURCE/'validation.json',OUT/'native/validation.json'),(WORK/'final-runtime-validation.json',OUT/'evidence/final-runtime-validation.json'),(WORK/'final-runtime.json',OUT/'evidence/final-runtime.json'),(WORK/'native-first-pass/validation.json',OUT/'evidence/first-pass/validation.json')]:shutil.copyfile(source,target)
record={'captures':rows,'count':39,'copied_byte_identical':True,'native_validation_sha256':sha(OUT/'native/validation.json'),'source_scope':validation['scope'],'evidence_hashes':{str(p.relative_to(OUT)):sha(p) for p in [OUT/'evidence/final-runtime-validation.json',OUT/'evidence/final-runtime.json',OUT/'evidence/root-native-art-review.json',OUT/'evidence/fighter-art-native-review.json',OUT/'evidence/first-pass/validation.json']},'not_live_user_battles':True,'profile_files_opened':validation['profile_files_opened'],'review_note':'Root reviewed 11 body sheets (88 shown sprites) and all 16 contexts; fighter_art reviewed the other 12 sheets (96 shown sprites). No visual defects observed. All final screenshots are byte-identical to the reviewed first-pass images. Sheets show 4 clips mirrored, not all40 unique poses.'}
(OUT/'native-manifest.json').write_text(json.dumps(record,indent=2,ensure_ascii=False)+'\n')
qa={'status':'passed','label':'QA nativa · 3832 comprobaciones, 0 fallos','description':'Godot nativo: 23 cuerpos, 39 PNG y 368 muestras de clips. Regresión headless: 6 suites, 56 484 comprobaciones, 0 fallos, incluido el gate estricto de 920 poses. Fixtures aisladas; no se abren perfiles ni se simulan recompensas.','checks':3832,'failures':0,'bodies':23,'captures':39,'runtime_checks':56484,'runtime_suites':6,'strict_checks_included':14977,'links':[{'href':'native/validation.json','label':'Resultado nativo'}, {'href':'evidence/final-runtime-validation.json','label':'Seis suites'}, {'href':'evidence/final-runtime.json','label':'Gate estricto'}, {'href':'native-manifest.json','label':'39 capturas y hashes'},{'href':'evidence/root-native-art-review.json','label':'Revisión visual · 11 láminas y16 contextos'},{'href':'evidence/fighter-art-native-review.json','label':'Revisión visual · 12 láminas'}],'first_pass':{'checks':3878,'failures':46,'validation':'evidence/first-pass/validation.json','reason':'La fixture exigía conservar desplazamiento de contacto en 46 KO de figuras sin rival. Se limitó esa aserción a la pareja; raíces y contención siguen comprobándose en figuras aisladas. No hubo un recorte de arte ni un cambio del runtime.'},'browser_qa':'Not performed: CUA Chrome unavailable; jsdom/happy-dom/linkedom are not installed in available local Node environments.'}
(OUT/'native-qa.json').write_text(json.dumps(qa,indent=2,ensure_ascii=False)+'\n')
names=json.loads((OUT/'manifest.json').read_text())['entries'];names={e['body_id']:e['name'] for e in names};phases={'guard':'Guardia','strike':'Golpe','reaction':'Reacción','ko':'KO'}
parts=['<section id="native"><h2>39 capturas nativas</h2><p>Son fixtures de clips con FighterView y BattleLayout de producción. No abren Main, perfiles o cuentas y no representan victorias de usuarios. Se prueban 23 cuerpos, cuatro acciones, dos tamaños y dos orientaciones; se conservan 23 láminas de ocho muestras y 16 contextos del piloto Roque.</p><p>Revisión visual completa: 11 láminas y 16 contextos por root; las otras 12 láminas por un segundo revisor. Sin defectos observados. Las láminas muestran cuatro clips en dos orientaciones: esta muestra nativa no equivale a ver las 40 poses únicas en movimiento.</p><p class="muted">La guardia común se muestra para revisar su animación; no concede esa técnica a personajes que no la poseen. Pulsa una imagen para abrir el PNG nativo completo.</p>']
for kind,title in [('context-','Contextos · Roque, escritorio y teléfono'),('sheet-','Elenco completo · ocho muestras por cuerpo')]:
 parts.append('<details open><summary>'+title+'</summary><div class="native-grid">')
 for e in rows:
  name=Path(e['path']).name
  if not name.startswith(kind):continue
  if kind=='sheet-':label=names.get(name[6:-4],name[6:-4])+' · lámina nativa'
  else:
   pieces=name[:-4].split('-');label='Roque · '+phases.get(pieces[2],pieces[2])+' · '+pieces[3]+' · '+('hacia la izquierda' if 'facing-1' in name else 'hacia la derecha')
  parts.append('<figure><a href="'+e['path']+'"><img loading="lazy" src="'+e['path']+'" alt="'+html.escape(label)+'"></a><figcaption>'+html.escape(label)+'</figcaption></figure>')
 parts.append('</div></details>')
parts.append('<details><summary>Primer pase conservado · corrección de la fixture</summary><p>El primer pase produjo 3878 comprobaciones y 46 fallos. Los 46 correspondían a una aserción de conservación del avance de contacto aplicada a actores sin rival: en esas muestras no existía avance que conservar. Se mantiene la aserción para parejas y se siguen verificando raíces y contención de los actores aislados. El runtime y los PNG no se editaron para resolverla.</p><p><a href="evidence/first-pass/validation.json">Resultado inicial</a> · <a href="evidence/final-runtime-validation.json">Corrección documentada y regresión</a> · <a href="native/validation.json">Pase final: 3832/0</a>.</p></details></section>')
(OUT/'native-section.html').write_text('\n'.join(parts))
print(json.dumps({'copied':len(rows),'checks':validation['checks'],'failures':validation['failures'],'manifest_sha256':sha(OUT/'native-manifest.json')}))
